### ISSUE TITLE
modernizr fails building frontend with gulp on docker version

### ISSUE THREAD

**Issue by eliwaksbaum** [DDMAL/cantus#402]
```
#14 2.448 [17:11:47] Starting 'build:modernizr'...
#14 2.450 [17:11:47] Finished 'clean:css' after 5.79 ms
#14 2.450 [17:11:47] Starting 'bundle:css'...
#14 2.592 [17:11:47] 'build:modernizr' errored after 143 ms
#14 2.592 [17:11:47] Error: ENOENT: no such file or directory, open '.tmp/modernizr.js'
#14 2.594 [17:11:47] 'build:js' errored after 154 ms
#14 2.594 [17:11:47] Error in plugin 'run-sequence(build:modernizr)'
#14 2.594 Message:
#14 2.594     ENOENT: no such file or directory, open '.tmp/modernizr.js'
#14 2.594 Details:
#14 2.594     errno: -2
#14 2.594     code: ENOENT
#14 2.594     syscall: open
#14 2.594     path: .tmp/modernizr.js
#14 2.594 Stack:
#14 2.594 Error: ENOENT: no such file or directory, open '.tmp/modernizr.js'
#14 2.595 [17:11:47] 'build:css' errored after 151 ms
#14 2.595 [17:11:47] Error in plugin 'run-sequence(build:js)'
#14 2.595 Message:
#14 2.595     ENOENT: no such file or directory, open '.tmp/modernizr.js'
#14 2.595 Details:
#14 2.595     errno: -2
#14 2.595     code: ENOENT
#14 2.595     syscall: open
#14 2.595     path: .tmp/modernizr.js
#14 2.595 Stack:
#14 2.595 Error: ENOENT: no such file or directory, open '.tmp/modernizr.js'
#14 2.596 [17:11:47] 'build:css' errored after 152 ms
#14 2.596 [17:11:47] Error in plugin 'run-sequence(build:modernizr)'
#14 2.596 Message:
#14 2.596     ENOENT: no such file or directory, open '.tmp/modernizr.js'
#14 2.596 Details:
#14 2.596     errno: -2
#14 2.596     code: ENOENT
#14 2.596     syscall: open
#14 2.596     path: .tmp/modernizr.js
#14 2.596 Stack:
#14 2.596 Error: ENOENT: no such file or directory, open '.tmp/modernizr.js'
#14 2.597 [17:11:47] 'build:modernizr' errored after 149 ms
#14 2.597 [17:11:47] Error: task completion callback called too many times
#14 2.597     at finish (/code/public/cantusdata/frontend/node_modules/orchestrator/lib/runTask.js:15:10)
#14 2.597     at cb (/code/public/cantusdata/frontend/node_modules/orchestrator/lib/runTask.js:29:3)
#14 2.597     at /code/public/cantusdata/frontend/gulpfile.js:156:21
#14 2.597     at FSReqWrap.args [as oncomplete] (fs.js:140:20)
#14 2.684 [17:11:48] Finished 'bundle:css' after 234 ms
```

I'm assuming it has something to do with this in the gulpfile:
```
modernizr.build(json, function (result)
        {
            mkdirp('.tmp');

            fs.writeFile('.tmp/modernizr.js', result, function (err)
            {
                if (err)
                    cb(err);
                else
                    cb();
            });
        });
```
I don't know why it's failing to create or see .tmp. On a whim I tried replacing mkdirp with fs.mkdir but got the same error.

I believe cutting out modernizr is what's stopping certain pages from rendering correctly. I had thought that wasn't the case since the errors were appearing on pages that were showing up fine as well, but I misunderstood the differences between how the html is delivered in different cases.

**Comment by eliwaksbaum** [comment]
By my understanding, what modernizr is doing for us is determining whether the user's browser supports flexbox. We can use this information in the scss file to selectively modify the final css to use flexbox when we can and workarounds when it's not supported.

**Comment by eliwaksbaum** [comment]
this seems like a relatively low priority feature, so for now I'm cutting out modernizr entirely, which is letting the manuscript and search pages function normally. On older browsers, the layout will be broken

**Comment by napulen** [comment]
@eliwaksbaum Can you pinpoint the browser compatibility before and after dropping `modernizr`?
