### ISSUE TITLE
django fails - "database is starting up"

### ISSUE THREAD

**Issue by eliwaksbaum** [DDMAL/cantus#414]
Sometimes when running docker-compose up we get the following error. Even though we're using wait-for-it to make sure postgres is running. It doesn't seem to cause the container to exit though, so we can't just add a restart:always
```
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection

    self.connect()

  File "/usr/local/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 200, in connect

    self.connection = self.get_new_connection(conn_params)

  File "/usr/local/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection

    connection = Database.connect(**conn_params)

  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect

    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)

psycopg2.OperationalError: FATAL:  the database system is starting up



The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "manage.py", line 22, in <module>

    main()

  File "manage.py", line 18, in main

    execute_from_command_line(sys.argv)

  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line

    utility.execute()

  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv

    self.execute(*args, **cmd_options)

  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute

    output = self.handle(*args, **options)

  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 85, in wrapped

    res = handle_func(*args, **kwargs)

  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 92, in handle

    executor = MigrationExecutor(connection, self.migration_progress_callback)

  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__

    self.loader = MigrationLoader(self.connection)

  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 53, in __init__

    self.build_graph()

  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 216, in build_graph

    self.applied_migrations = recorder.applied_migrations()

  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations

    if self.has_table():

  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 55, in has_table

    with self.connection.cursor() as cursor:

  File "/usr/local/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 259, in cursor

    return self._cursor()

  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 235, in _cursor

    self.ensure_connection()

  File "/usr/local/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection

    self.connect()

  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection

    self.connect()

  File "/usr/local/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 200, in connect

    self.connection = self.get_new_connection(conn_params)

  File "/usr/local/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection

    connection = Database.connect(**conn_params)

  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect

    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)

django.db.utils.OperationalError: FATAL:  the database system is starting up
```

**Comment by napulen** [comment]
Any hope in finding a deterministic way to reproduce this?
